# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

#runs in Macos windows and linux

trigger:
- main

#pool:
 # vmImage: ubuntu-latest
strategy:
  matrix:
    linux:
      imageName: "ubuntu-latest"
  #  mac:
  #    imageName: "macOS-latest"
  #  windows:
  #    imageName: "windows-latest"
  maxParallel: 3

pool:
  vmImage: $(imageName)

steps:
- task: Maven@3
  inputs:
    
    mavenPomFile: 'com/pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.8'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    goals: 'package'

- task: PublishPipelineArtifact@1
  inputs:
    targetPath: '$(Pipeline.Workspace)'
    artifact: 'publishpipelinertifactbuddy'
    publishLocation: 'pipeline'
  condition: succeededOrFailed()
- #task: CopyFiles@2
  #inputs:
    #contents: '**/*.html'
    #targetFolder: $(Build.ArtifactStagingDirectory)
  #condition: succeededOrFailed()
- task: CopyFiles@2
  inputs:
    contents: '**/reports/*.html'
    targetFolder: $(Build.ArtifactStagingDirectory)
  condition: succeededOrFailed()
- task: PublishBuildArtifacts@1
  inputs:
    pathToPublish: $(Build.ArtifactStagingDirectory)
    artifactName: MyBuildOutputs
  condition: succeededOrFailed()
- #task: DownloadPipelineArtifact@2
  #inputs:
    #artifact: 'repor'
    #patterns: '**/*.html'
    #path: $(Pipeline.Workspace)